name: Longinus Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  code-quality:
    name: Форматування та Аналіз
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Code Formatting
        run: dotnet format whitespace --verify-no-changes

      - name: Static Analysis
        run: dotnet format analyzers --verify-no-changes